name: shixuzhipei
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: 2.2.1
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - stitch/assets/images/
  
  fonts:
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/NotoSerifSC-Subset.ttf
    - family: StitchInter
      fonts:
        - asset: stitch/assets/fonts/bad5f68b18b9.ttf
          weight: 400
        - asset: stitch/assets/fonts/11e1d80f42f9.ttf
          weight: 500
        - asset: stitch/assets/fonts/e9191f0db3ed.ttf
          weight: 600
        - asset: stitch/assets/fonts/1be3d765b0bd.ttf
          weight: 700
