import 'package:flutter/material.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _data = {
    'zh': {
      'app_title': '时序智配 BattleMan',

      // Bottom navigation
      'nav_focus': '专注',
      'nav_schedule': '日程',
      'nav_micro': '微任务',
      'nav_team': '团队',
      'nav_profile': '我的',

      // Common buttons
      'btn_add': '添加',
      'btn_cancel': '取消',
      'btn_confirm': '确认',
      'btn_delete': '删除',
      'btn_save': '保存',
      'btn_start': '开始',
      'btn_pause': '暂停',
      'btn_finish': '完成',
      'btn_completed': '已完成',
      'btn_incomplete': '未完成',
      'btn_ok': '确定',
      'btn_check': '检查',
      'btn_import': '导入',

      // Common labels
      'label_title': '标题',
      'label_tag': '标签',
      'label_desc': '描述(可选)',
      'label_date': '日期',
      'label_duration': '时长(分钟):',
      'label_start_time': '开始时间:',
      'label_start': '开始',
      'label_minutes': '分钟',
      'label_priority': '优先级',
      'label_cognitive_load': '认知负荷',

      // Dialogs
      'dialog_add_title': '新增日程',
      'dialog_del_title': '删除',
      'dialog_del_content': '确认删除',

      // Common tooltips / states
      'tooltip_more': '更多',
      'common_loading': '加载中...',
      'common_ok': '成功',
      'common_fail': '失败',
      'common_count': '数量',
      'common_at': '时间',
      'common_path': '路径',
      'common_error': '错误',
      'common_unknown': '未知',

      // Focus page
      'focus_title': '当下专注',
      'focus_status_label': '当前状态:',
      'status_flow_value': '高效 (Flow)',
      'status_flow_desc': '状态稳定，适合深度工作',
      'focus_header_current': '当前任务',
      'focus_header_next': '后续待办',
      'focus_empty_task': '今日已无更多日程',
      'focus_time_remaining': '剩余时间: ',
      'focus_snack_start': '将于 {min} 分钟后开始 {task}',
      'focus_snack_upcoming': '{task} 将于 {min} 分钟后开始...',
      'focus_time_crystal_title': '时间晶体推荐',
      'focus_time_crystal_empty': '暂无可用空档或微任务。',
      'focus_time_crystal_subtitle':
          '{start} | {minutes} 分钟（{bucket}） | {taskMinutes} 分钟',
      'focus_btn_one_click_insert': '一键插入',

      // Calendar page
      'calendar_title': '智能日程',
      'calendar_view_day': '日',
      'calendar_view_week': '周',
      'calendar_week_empty': '暂无日程',
      'color_green': '绿色',
      'color_blue': '蓝色',
      'color_orange': '橙色',
      'calendar_tooltip_switch_to_smart': '切换到智能规划',
      'calendar_tooltip_switch_to_manual': '切换到手动模式',
      'calendar_tooltip_insert_urgent': '插入紧急任务并重新规划',
      'calendar_tooltip_export_ics': '导出 iCal（ICS）',
      'calendar_tooltip_import_ics': '导入 iCal（粘贴 ICS）',
      'calendar_btn_replan': '重新规划',
      'calendar_status_not_started': '未开始',
      'calendar_status_in_progress': '进行中',
      'calendar_status_done': '已完成',
      'calendar_status_overdue': '已超时',
      'calendar_planner_issues': '规划器提示：{count} 项',
      'calendar_insert_urgent_title': '插入紧急任务',
      'calendar_insert_urgent_default_title': '紧急：解除阻塞',
      'calendar_insert_urgent_confirm': '插入并重新规划',
      'calendar_seed_architecture_design': '架构设计',
      'calendar_seed_email_triage': '邮件清理',
      'calendar_seed_spec_review': '需求评审',
      'calendar_seed_implementation_sprint': '实现冲刺',
      'calendar_reminder_label': '提醒',
      'calendar_reminder_none': '不提醒',
      'calendar_reminder_suffix': '分钟（开始前）',
      'calendar_repeat_label': '重复',
      'calendar_repeat_none': '不重复',
      'calendar_repeat_daily': '每天',
      'calendar_repeat_weekly': '每周',
      'calendar_repeat_monthly': '每月',
      'calendar_repeat_until': '截止',
      'calendar_repeat_until_none': '无截止',
      'calendar_ics_exported_path': 'ICS 已导出：{path}',
      'calendar_ics_exported_download': 'ICS 已导出（下载）：{fileName}',
      'calendar_ics_export_failed': 'ICS 导出失败：{error}',
      'calendar_ics_import_title': '导入 iCal（ICS）',
      'calendar_ics_import_help':
          '粘贴 ICS 文本。重复规则（RRULE）会被忽略；时间按本地时区处理。',
      'calendar_ics_import_hint': 'BEGIN:VCALENDAR...\nEND:VCALENDAR',
      'calendar_ics_import_success': '已导入 {added} 个事件。',
      'calendar_ics_import_updated': '已同步更新 {updated} 条变更。',
      'calendar_ics_import_failed': '导入失败：{error}',

      // Built-in tags (display only)
      'tag_general': '通用',
      'tag_deep_work': '深度工作',
      'tag_micro_task': '微任务',
      'tag_routine': '常规',
      'tag_urgent': '紧急',
      'tag_goal': '目标',

      // Micro tasks
      'micro_title': '微任务晶体池',
      'micro_ai_suggestion': 'AI 识别到你现在有约 15 分钟碎片时间，建议处理以下任务:',
      'micro_btn_fill': '一键填充',
      'micro_btn_add': '添加微任务',
      'micro_dialog_add': '新增微任务',
      'micro_dialog_del': '删除微任务',
      'micro_dialog_edit': '编辑微任务',
      'micro_label_min': '预计分钟:',
      'micro_card_min': '分钟',
      'micro_batch_enter': '批量完成',
      'micro_batch_exit': '退出批量',
      'micro_batch_selected': '已选 {count}',
      'micro_batch_schedule': '集中安排',
      'micro_batch_need_select': '请先选择微任务',
      'micro_batch_need_same_tag': '集中安排需要选择同一标签的任务',
      'micro_batch_default_title': '{minutes} 分钟 {tag} batch',
      'micro_schedule_dialog_title': '同类集中安排',

      // Team
      'team_title': '团队协作',
      'team_rec_title': '协作黄金窗口推荐',
      'team_best_time': '最佳会议时间: 今日 15:00 - 16:00',
      'team_btn_book': '发起预约',
      'team_reason': '理由: 多人空闲且能量状态满足阈值',
      'team_track_title': '项目进度追踪',
      'team_btn_add_task': '添加任务',
      'team_dialog_add': '添加团队任务',
      'team_label_name': '成员姓名',
      'team_label_role': '角色',
      'team_label_task': '任务标题',
      'team_label_progress': '进度',
      'team_label_high_energy': '高效状态',
      'team_label_due': '到期时间:',
      'team_card_ongoing': '正在进行:',
      'team_card_due': '到期:',
      'team_meeting_title': '团队会议',
      'team_snack_booked_meeting': '已预约会议：{time}',
      'team_conflict_check_title': '冲突检查',
      'team_conflicts_title': '冲突',
      'team_no_conflicts': '暂无冲突。',
      'team_busy_members': '忙碌成员：{members}',
      'team_golden_windows_header': '黄金窗口（>= {participants} 人，>= {energy}）',
      'team_golden_windows_empty':
          '未找到共同空档。可用右上角放大镜进行冲突检查，或稍后调整能量阈值。',
      'team_free_members': '空闲成员：{count}',
      'team_merged_schedule_today': '合并团队日程（今天）',
      'team_busy_overlap_title': '忙碌重叠（冲突提示）',
      'team_busy_overlap_empty': '未检测到重叠。',
      'team_member_subtitle': '能量：{energy} | 共享：{perm} | 忙碌块：{count}',
      'team_no_members': '未找到团队成员。',
      'team_legend_golden': '黄金窗口',
      'team_legend_busy_overlap': '忙碌重叠',
      'team_legend_conflict_probe': '冲突探测',
      'team_recommended': '推荐',
      'team_probe_ok': '探测：{time}（{minutes} 分钟）无冲突。',
      'team_probe_conflict': '探测：{time}（{minutes} 分钟）冲突成员：{members}',
      'team_busy': '忙碌',
      'team_dialog_member': '成员：{name}',
      'team_dialog_start': '开始：{time}',
      'team_dialog_duration': '时长：{minutes} 分钟',
      'team_dialog_tag': '标签：{tag}',

      // Profile & settings
      'profile_title': '效率画像',
      'profile_device': '设备连接 (Apple Watch/Huawei)',
      'profile_connected': '已连接',
      'profile_auth': '第三方应用授权 (MCP)',
      'profile_model_card': 'AI 认知效率模型 (每周更新)',
      'settings_title': '系统设置',
      'settings_language': '更改语言',
      'settings_notify': '通知管理',
      'settings_dark': '外观模式',
      'theme_system': '跟随系统',
      'theme_light': '浅色模式',
      'theme_dark': '深色模式',
      'lang_zh': '中文 (简体)',
      'lang_en': 'English',

      // Review
      'review_title': '智能复盘',
      'review_tooltip_prev_week': '上一周',
      'review_tooltip_next_week': '下一周',
      'review_btn_simulate_week': '模拟一周',
      'review_btn_generate_report': '生成报告',
      'review_empty': '暂无报告，可先模拟或生成。',
      'review_metric_completion': '完成率',
      'review_metric_time': '时间',
      'review_metric_time_value': '计划 {planned} 分钟，实际 {actual} 分钟',
      'review_section_duration_buckets': '实际时长分桶',
      'review_section_delay_attribution': '延误归因（规则）',
      'review_suggestions_title': '建议',
      'review_suggestions_empty': '本周暂无建议。',
      'review_tuning_title': '调度参数（已保存）',
      'review_tuning_default_duration_multiplier': '默认时长倍率：{value}',
      'review_tuning_high_load_penalty_low_energy': '低能量时高负荷惩罚：{value}',
      'review_tuning_tag_multiplier_none': '标签时长倍率：无',
      'review_tuning_tag_multiplier_entry': '标签时长倍率[{tag}] = {value}',
      'review_tip_replan': '提示：前往“日程 -> 智能模式”，点击重新规划以查看参数生效。',
      'review_snack_simulated': '已模拟 1 周，报告已生成并保存调度参数。',

      // Diagnostics
      'diag_title': '运行自检 / 调试面板',
      'diag_section_data': '数据源',
      'diag_section_storage': '本地存储',
      'diag_section_perf': '调度性能',
      'diag_section_ics': '导入导出 (ICS)',
      'diag_section_logs': '关键日志 (可导出)',
      'diag_btn_clear': '清空日志',
      'diag_btn_export': '导出日志',
      'diag_logs_empty': '暂无日志。去“智能日程 / 团队协作”等页面操作以产生日志。',
      'diag_tooltip_refresh': '刷新',
      'diag_tooltip_export_logs': '导出日志',
      'diag_export_failed': '日志导出失败：{error}',
      'diag_export_ok': '日志已导出。',
      'diag_export_ok_path': '日志已导出：{path}',
      'diag_kv_data_service': '数据服务',
      'diag_kv_local': '本地',
      'diag_kv_remote': '远端',
      'diag_kv_backend': '后端',
      'diag_kv_exists': '是否存在',
      'diag_kv_bytes': '大小（字节）',
      'diag_kv_replan_triggers': '重规划触发次数',
      'diag_kv_last_plan_cost_ms': '上次规划耗时（毫秒）',
      'diag_kv_last_plan_at': '上次规划时间',
      'diag_kv_last_plan_reason': '上次规划原因',
      'diag_kv_last_export': '上次导出',
      'diag_kv_last_import': '上次导入',
      'log_level_debug': '调试',
      'log_level_info': '信息',
      'log_level_warn': '警告',
      'log_level_error': '错误',

      // Emotion
      'emo_title': '情绪感知',
      'emo_current': '当前情绪',
      'emo_quick': '快速打卡',
      'emo_today': '今日记录',
      'emo_today_empty': '今天还没有情绪打卡记录。',
      'emo_checkin_title': '情绪打卡',
      'emo_note': '备注(可选)',
      'emo_checked_in': '已记录',
      'emo_efficient': '高效',
      'emo_stable': '平稳',
      'emo_tired': '疲惫',
      'emo_irritable': '烦躁',
      'emo_care_hint': '检测到情绪连续偏低。是否考虑减少未来 1-2 天任务量，优先安排低压力任务并补充休息？',

      // Goals
      'goal_title': '目标规划',
      'goal_add': '新建目标',
      'goal_add_title': '新建目标',
      'goal_delete_title': '删除目标',
      'goal_due': '截止日期',
      'goal_pick_date': '选择日期',
      'goal_priority': '优先级',
      'goal_hint': '系统将自动拆解为一组可执行任务，并可一键落地到日程。',
      'goal_tasks': '任务拆解',
      'goal_schedule_next': '安排下一个任务',
      'goal_all_done': '该目标任务已全部完成。',
      'goal_no_slot': '今天没有找到合适的空档，请先调整日程或缩短任务时长。',
      'goal_scheduled': '已加入日程',
      'goal_empty': '暂无目标，点击右下角创建。',

      // MCP
      'mcp_title': '多应用融合监听 (MCP)',
      'mcp_hint': '把第三方通知/邮件/会议消息粘贴到下面，系统会提取时间与主题并生成日程。',
      'mcp_placeholder': '示例:\nUID: zoom-123\n主题: 客户会议\n时间: 2026-03-16 15:00\n时长: 60 分钟\n或:\n明天下午3点 客户会议 60分钟',
      'mcp_btn_parse': '解析',
      'mcp_btn_import': '生成日程',
      'mcp_preview': '解析预览',
      'mcp_parse_fail': '未识别到可用的时间信息(建议包含“2026-03-16 15:00”或“明天下午3点”)',
      'mcp_imported': '已生成日程。',
      'mcp_updated': '日程已同步。',
      'mcp_change_synced': '变更已同步。',

      // Enums
      'energy_tier_very_low': '极低',
      'energy_tier_low': '偏低',
      'energy_tier_medium': '中等',
      'energy_tier_high': '偏高',
      'energy_tier_very_high': '极高',
      'team_share_permission_none': '不共享',
      'team_share_permission_free_busy': '仅空闲/忙碌',
      'team_share_permission_details': '共享详情',
      'cognitive_load_low': '低',
      'cognitive_load_medium': '中',
      'cognitive_load_high': '高',
    },
    'en': {
      'app_title': 'BattleMan',

      'nav_focus': 'Focus',
      'nav_schedule': 'Schedule',
      'nav_micro': 'Micro',
      'nav_team': 'Team',
      'nav_profile': 'Profile',

      'btn_add': 'Add',
      'btn_cancel': 'Cancel',
      'btn_confirm': 'Confirm',
      'btn_delete': 'Delete',
      'btn_save': 'Save',
      'btn_start': 'Start',
      'btn_pause': 'Pause',
      'btn_finish': 'Complete',
      'btn_completed': 'Completed',
      'btn_incomplete': 'Incomplete',
      'btn_ok': 'OK',
      'btn_check': 'Check',
      'btn_import': 'Import',

      'label_title': 'Title',
      'label_tag': 'Tag',
      'label_desc': 'Description (Optional)',
      'label_date': 'Date',
      'label_duration': 'Duration (mins):',
      'label_start_time': 'Start Time:',
      'label_start': 'Start',
      'label_minutes': 'Minutes',
      'label_priority': 'Priority',
      'label_cognitive_load': 'Load',

      'dialog_add_title': 'New Schedule',
      'dialog_del_title': 'Delete',
      'dialog_del_content': 'Delete',

      'tooltip_more': 'More',
      'common_loading': 'Loading...',
      'common_ok': 'OK',
      'common_fail': 'FAIL',
      'common_count': 'Count',
      'common_at': 'At',
      'common_path': 'Path',
      'common_error': 'Error',
      'common_unknown': 'Unknown',

      'focus_title': 'Focus Now',
      'focus_status_label': 'Status:',
      'status_flow_value': 'Flow State',
      'status_flow_desc': 'Stable state, ready for deep work',
      'focus_header_current': 'Current Task',
      'focus_header_next': 'Upcoming',
      'focus_empty_task': 'No more schedules for today',
      'focus_time_remaining': 'Time Left: ',
      'focus_snack_start': 'Starting {task} in {min} min',
      'focus_snack_upcoming': '{task} will start in {min} min...',
      'focus_time_crystal_title': 'Time Crystal Recommendations',
      'focus_time_crystal_empty': 'No available gaps or micro tasks.',
      'focus_time_crystal_subtitle':
          '{start} | {minutes} min ({bucket}) | {taskMinutes} min',
      'focus_btn_one_click_insert': 'One-click insert',

      'calendar_title': 'Smart Schedule',
      'calendar_view_day': 'Day',
      'calendar_view_week': 'Week',
      'calendar_week_empty': 'No events',
      'color_green': 'Green',
      'color_blue': 'Blue',
      'color_orange': 'Orange',
      'calendar_tooltip_switch_to_smart': 'Switch to smart plan',
      'calendar_tooltip_switch_to_manual': 'Switch to manual mode',
      'calendar_tooltip_insert_urgent': 'Insert urgent task and replan',
      'calendar_tooltip_export_ics': 'Export iCal (ICS)',
      'calendar_tooltip_import_ics': 'Import iCal (paste ICS)',
      'calendar_btn_replan': 'Replan',
      'calendar_status_not_started': 'Not started',
      'calendar_status_in_progress': 'In progress',
      'calendar_status_done': 'Done',
      'calendar_status_overdue': 'Overdue',
      'calendar_planner_issues': 'Planner issues: {count}',
      'calendar_insert_urgent_title': 'Insert urgent task',
      'calendar_insert_urgent_default_title': 'Urgent: unblock',
      'calendar_insert_urgent_confirm': 'Insert and replan',
      'calendar_seed_architecture_design': 'Architecture design',
      'calendar_seed_email_triage': 'Email triage',
      'calendar_seed_spec_review': 'Spec review',
      'calendar_seed_implementation_sprint': 'Implementation sprint',
      'calendar_reminder_label': 'Reminder',
      'calendar_reminder_none': 'None',
      'calendar_reminder_suffix': 'min before',
      'calendar_repeat_label': 'Repeat',
      'calendar_repeat_none': 'None',
      'calendar_repeat_daily': 'Daily',
      'calendar_repeat_weekly': 'Weekly',
      'calendar_repeat_monthly': 'Monthly',
      'calendar_repeat_until': 'Until',
      'calendar_repeat_until_none': 'No end',
      'calendar_ics_exported_path': 'ICS exported: {path}',
      'calendar_ics_exported_download': 'ICS exported (download): {fileName}',
      'calendar_ics_export_failed': 'ICS export failed: {error}',
      'calendar_ics_import_title': 'Import iCal (ICS)',
      'calendar_ics_import_help':
          'Paste ICS text. Recurrence (RRULE) is ignored; times are treated as local.',
      'calendar_ics_import_hint': 'BEGIN:VCALENDAR...\nEND:VCALENDAR',
      'calendar_ics_import_success': 'Imported {added} events.',
      'calendar_ics_import_updated': 'Synced {updated} updates.',
      'calendar_ics_import_failed': 'Import failed: {error}',

      'tag_general': 'General',
      'tag_deep_work': 'Deep work',
      'tag_micro_task': 'Micro task',
      'tag_routine': 'Routine',
      'tag_urgent': 'Urgent',
      'tag_goal': 'Goal',

      'micro_title': 'Micro Task Pool',
      'micro_ai_suggestion': 'AI detected you have about 15 minutes now. Suggested tasks:',
      'micro_btn_fill': 'One-Click Fill',
      'micro_btn_add': 'Add Micro Task',
      'micro_dialog_add': 'Add Micro Task',
      'micro_dialog_del': 'Delete Micro Task',
      'micro_dialog_edit': 'Edit Micro Task',
      'micro_label_min': 'Est. Minutes:',
      'micro_card_min': 'mins',
      'micro_batch_enter': 'Batch mode',
      'micro_batch_exit': 'Exit batch',
      'micro_batch_selected': 'Selected {count}',
      'micro_batch_schedule': 'Batch schedule',
      'micro_batch_need_select': 'Select micro tasks first',
      'micro_batch_need_same_tag': 'Batch schedule requires same tag',
      'micro_batch_default_title': '{minutes} min {tag} batch',
      'micro_schedule_dialog_title': 'Batch Schedule by Tag',

      'team_title': 'Team Collaboration',
      'team_rec_title': 'Golden Collaboration Windows',
      'team_best_time': 'Best time: Today 15:00 - 16:00',
      'team_btn_book': 'Book',
      'team_reason': 'Reason: common free window and energy threshold met',
      'team_track_title': 'Progress Tracking',
      'team_btn_add_task': 'Add Task',
      'team_dialog_add': 'Add Team Task',
      'team_label_name': 'Name',
      'team_label_role': 'Role',
      'team_label_task': 'Task',
      'team_label_progress': 'Progress',
      'team_label_high_energy': 'High Energy',
      'team_label_due': 'Due:',
      'team_card_ongoing': 'Ongoing:',
      'team_card_due': 'Due:',
      'team_meeting_title': 'Team meeting',
      'team_snack_booked_meeting': 'Booked meeting at {time}',
      'team_conflict_check_title': 'Check conflicts',
      'team_conflicts_title': 'Conflicts',
      'team_no_conflicts': 'No conflicts.',
      'team_busy_members': 'Busy members: {members}',
      'team_golden_windows_header': 'Golden windows (>= {participants}, >= {energy})',
      'team_golden_windows_empty':
          'No common window found. Try conflict check (magnifier) or adjust energy threshold later.',
      'team_free_members': 'Free members: {count}',
      'team_merged_schedule_today': 'Merged team schedule (today)',
      'team_busy_overlap_title': 'Busy overlap (conflict hints)',
      'team_busy_overlap_empty': 'No overlaps detected.',
      'team_member_subtitle': 'Energy: {energy} | Share: {perm} | Busy blocks: {count}',
      'team_no_members': 'No team members found.',
      'team_legend_golden': 'Golden window',
      'team_legend_busy_overlap': 'Busy overlap',
      'team_legend_conflict_probe': 'Conflict probe',
      'team_recommended': 'Recommended',
      'team_probe_ok': 'Probe: {time} ({minutes}m) is conflict-free.',
      'team_probe_conflict': 'Probe: {time} ({minutes}m) conflicts with: {members}',
      'team_busy': 'Busy',
      'team_dialog_member': 'Member: {name}',
      'team_dialog_start': 'Start: {time}',
      'team_dialog_duration': 'Duration: {minutes} min',
      'team_dialog_tag': 'Tag: {tag}',

      'profile_title': 'Efficiency Profile',
      'profile_device': 'Device Connection',
      'profile_connected': 'Connected',
      'profile_auth': 'Third-Party Auth (MCP)',
      'profile_model_card': 'Cognitive Profile Model (Weekly)',
      'settings_title': 'Settings',
      'settings_language': 'Language',
      'settings_notify': 'Notifications',
      'settings_dark': 'Appearance',
      'theme_system': 'System',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'lang_zh': 'Chinese',
      'lang_en': 'English',

      'review_title': 'Smart Review',
      'review_tooltip_prev_week': 'Previous week',
      'review_tooltip_next_week': 'Next week',
      'review_btn_simulate_week': 'Simulate 1 Week',
      'review_btn_generate_report': 'Generate Report',
      'review_empty': 'No report yet. Simulate or generate.',
      'review_metric_completion': 'Completion',
      'review_metric_time': 'Time',
      'review_metric_time_value': 'Planned {planned}m, Actual {actual}m',
      'review_section_duration_buckets': 'Actual Duration Buckets',
      'review_section_delay_attribution': 'Delay Attribution (rules)',
      'review_suggestions_title': 'Suggestions',
      'review_suggestions_empty': 'No suggestions this week.',
      'review_tuning_title': 'Scheduling Tuning (saved)',
      'review_tuning_default_duration_multiplier':
          'Default duration multiplier: {value}',
      'review_tuning_high_load_penalty_low_energy':
          'High-load penalty when low energy: {value}',
      'review_tuning_tag_multiplier_none': 'Tag duration multipliers: (none)',
      'review_tuning_tag_multiplier_entry':
          'Tag duration multiplier [{tag}]: {value}',
      'review_tip_replan':
          'Tip: Go to Schedule -> Smart mode and replan to see the tuning take effect.',
      'review_snack_simulated':
          'Simulated 1 week. Report generated and tuning saved.',

      'diag_title': 'Diagnostics',
      'diag_section_data': 'Data Source',
      'diag_section_storage': 'Local Storage',
      'diag_section_perf': 'Scheduling Performance',
      'diag_section_ics': 'ICS Import/Export',
      'diag_section_logs': 'Logs',
      'diag_btn_clear': 'Clear',
      'diag_btn_export': 'Export',
      'diag_logs_empty': 'No logs yet. Try actions in Schedule/Team pages.',
      'diag_tooltip_refresh': 'Refresh',
      'diag_tooltip_export_logs': 'Export Logs',
      'diag_export_failed': 'Log export failed: {error}',
      'diag_export_ok': 'Logs exported.',
      'diag_export_ok_path': 'Logs exported: {path}',
      'diag_kv_data_service': 'Data service',
      'diag_kv_local': 'Local',
      'diag_kv_remote': 'Remote',
      'diag_kv_backend': 'Backend',
      'diag_kv_exists': 'Exists',
      'diag_kv_bytes': 'Bytes',
      'diag_kv_replan_triggers': 'Replan triggers',
      'diag_kv_last_plan_cost_ms': 'Last plan cost (ms)',
      'diag_kv_last_plan_at': 'Last plan at',
      'diag_kv_last_plan_reason': 'Last plan reason',
      'diag_kv_last_export': 'Last export',
      'diag_kv_last_import': 'Last import',
      'log_level_debug': 'DEBUG',
      'log_level_info': 'INFO',
      'log_level_warn': 'WARN',
      'log_level_error': 'ERROR',

      'emo_title': 'Emotion',
      'emo_current': 'Current',
      'emo_quick': 'Quick Check-in',
      'emo_today': 'Today',
      'emo_today_empty': 'No check-ins today.',
      'emo_checkin_title': 'Emotion Check-in',
      'emo_note': 'Note (Optional)',
      'emo_checked_in': 'Recorded',
      'emo_efficient': 'Efficient',
      'emo_stable': 'Stable',
      'emo_tired': 'Tired',
      'emo_irritable': 'Irritable',
      'emo_care_hint': 'Your emotion state looks low for 2 days. Consider reducing workload and adding more rest.',

      'goal_title': 'Goals',
      'goal_add': 'New Goal',
      'goal_add_title': 'New Goal',
      'goal_delete_title': 'Delete Goal',
      'goal_due': 'Due',
      'goal_pick_date': 'Pick Date',
      'goal_priority': 'Priority',
      'goal_hint': 'We will decompose it into tasks and can schedule them.',
      'goal_tasks': 'Tasks',
      'goal_schedule_next': 'Schedule Next Task',
      'goal_all_done': 'All tasks done.',
      'goal_no_slot': 'No slot found today.',
      'goal_scheduled': 'Added to schedule',
      'goal_empty': 'No goals yet.',

      'mcp_title': 'MCP Ingest',
      'mcp_hint': 'Paste external messages and generate schedule entries.',
      'mcp_placeholder': 'Example:\nUID: zoom-123\nTitle: Customer Meeting\nTime: 2026-03-16 15:00\nDuration: 60 min',
      'mcp_btn_parse': 'Parse',
      'mcp_btn_import': 'Import',
      'mcp_preview': 'Preview',
      'mcp_parse_fail': 'No time detected.',
      'mcp_imported': 'Imported.',
      'mcp_updated': 'Synced.',
      'mcp_change_synced': 'Changes synced.',

      'energy_tier_very_low': 'Very low',
      'energy_tier_low': 'Low',
      'energy_tier_medium': 'Medium',
      'energy_tier_high': 'High',
      'energy_tier_very_high': 'Very high',
      'team_share_permission_none': 'None',
      'team_share_permission_free_busy': 'Free/busy',
      'team_share_permission_details': 'Details',
      'cognitive_load_low': 'Low',
      'cognitive_load_medium': 'Medium',
      'cognitive_load_high': 'High',
    },
  };

  static String of(
    BuildContext context,
    String key, {
    Map<String, String>? params,
  }) {
    final locale = Localizations.localeOf(context).languageCode;
    final lang = (locale == 'en') ? 'en' : 'zh';
    String text = _data[lang]?[key] ?? key;

    if (params != null) {
      params.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }
    return text;
  }
}
